---
title: "week3"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
! Run the week2 assignment first !
```{r}
library(deSolve)
```
### Assignment 1: assess model validity

## [1]
Plotting the mean is good practice because we expect a good model to resemble the median.
So by plotting the median of the experimental data we can check if our model is any good.


## [2]
```{r}
#read data
data <- read.csv("MPL.csv", na.strings = "NA")
median_MPL_01 <- median(data$MPL_conc[data$dose==0.1], na.rm=T)
median_MPL_01 

medians <- aggregate(data[,c("MPL_conc","mRNA","Free_receptor")],list(data$dose,data$time), median, na.rm=T)
names(medians)[1:2] <- c("dose","time")

#prepare data for plotting
m.d.3 <- subset(medians, dose == 0.3)
m.d.1 <- subset(medians, dose == 0.1)
d.3 <- subset(data, dose == 0.3)
d.1 <- subset(data, dose == 0.1)
out.1 <- as.data.frame(out.1)
out.3 <- as.data.frame(out.3)

#plots for 0.3 dose
plot( m.d.3$time, m.d.3$mRNA,type = "l", col = "red")
lines(out.3$time, out.3$mRNAr)
points(d.3$time, d.3$mRNA, pch="*")

plot(m.d.3$time, m.d.3$Free_receptor, type = "l", col = "red")
lines(out.3$time, out.3$R)
points(d.3$time, d.3$Free_receptor, pch="*")

#plots for 0.1 dose
plot( m.d.1$time, m.d.1$mRNA,type = "l", col = "red")
lines(out.1$time, out.1$mRNAr)
points(d.1$time, d.1$mRNA, pch="*")

plot(m.d.1$time, m.d.1$Free_receptor, type = "l", col = "red")
lines(out.1$time, out.1$R)
points(d.1$time, d.1$Free_receptor, pch="*")
```


## [3]


###  Assignment 2: simulate scenario’s 

### [1]
If the drug has no influence on the synthesis of mRNA you would expect



```{r}
formula_2 <- function(t,y,parms){
  with(as.list(c(y,parms)),{
         D <- D * 1000 * (1 / 374.471)
         dmRNAr <- ks_Rm * (1 - DRN/(IC50_Rm+DRN)) - kd_Rm * mRNAr
         dR <- ks_r * mRNAr + Rf *kre *DRN - kon  * R - kd_R * R
         dDR <- kon  * R - kT *DR
         dDRN <- kT * DR - kre * DRN
         return(list(c(dmRNAr ,dR ,dDR, dDRN)))

       }
       )
}

parameters <- c(ks_Rm = 2.90, IC50_Rm = 26.2, kd_Rm = 0.612, ks_r = 3.22, Rf = 0.49, kre = 0.57, kon = 0.00329, kd_R = 0.0572, kT = 0.63, D = 14.59 )
state = c(mRNAr = 4.74, R = 267 ,DR = 0, DRN = 0)
times <- seq(0, 168,  by = 1)
out  <- ode(times = times, y = state, parms = parameters, func = formula_2, method = "euler")
plot(out)
```


### [2]

```{r}
formula_3 <- function(t,y,parms){
  with(as.list(c(y,parms)),{
         D <- D * 1000 * (1 / 374.471)
         dmRNAr <- ks_Rm * (1 - DRN/(IC50_Rm+DRN)) - kd_Rm * mRNAr
         dR <- ks_r * mRNAr + Rf *kre *DRN - kon  * R - kd_R * R
         dDR <- kon  * R - kT *DR
         dDRN <- kT * DR - kre * DRN
         return(list(c(dmRNAr ,dR ,dDR, dDRN)))
       }
       )
}

parameters <- c(ks_Rm = 2.90, IC50_Rm = 26.2, kd_Rm = 0.612, ks_r = 3.22, Rf = 0.49, kre = 0.57, kon = 0.00329, kd_R = 0.0572, kT = 0.63, D = 14.59 )
state = c(mRNAr = 4.74, R = 267 ,DR = 0, DRN = 0)
times <- seq(0, 168,  by = 1)
out  <- ode(times = times, y = state, parms = parameters, func = formula_3, method = "euler")
plot(out)
```









