---
output:
  pdf_document: default
  html_document: default
---
```{r echo=FALSE}
library(deSolve)
library(icesTAF)
parameters <- read.table("parameters.txt", sep="\t")
colnames(parameters) <- parameters[1,]
parameters <- parameters[2:nrow(parameters),]
```

```{r error=FALSE, warning=FALSE, echo=FALSE}
parameters.spring <- c(b=500, Îº=8000, Ïƒ1=0.25, Ïƒ2=1.5, Î·0=0, Î·1=0, Ï•0=0.08511, Ï•1=0.16936, Î±=0.55, Î³=0.2061, Î´=0.006570, Î±_t=0.14, Î»=10000, n=2, p=1, ðœ‰=8)
parameters.summer <- c(b=1500, Îº=12000, Ïƒ1=0.25, Ïƒ2=1.5, Î·0=0, Î·1=0, Ï•0=0.08511, Ï•1=0.16936, Î±=0.12, Î³=0.2835, Î´=0.023300, Î±_t=0.14, Î»=10000, n=2, p=0, ðœ‰=8)
parameters.fall <- c(b=500, Îº=8000, Ïƒ1=0.25, Ïƒ2=1.5, Î·0=0, Î·1=0, Ï•0=0.08511, Ï•1=0.16936, Î±=0.24, Î³=0.2527, Î´=0.015683, Î±_t=0.14, Î»=10000, n=2, p=0, ðœ‰=8)
parameters.winter <- c(b=0, Îº=6000, Ïƒ1=0, Ïƒ2=1.5, Î·0=0.00649, Î·1=0.00649, Ï•0=0, Ï•1=0, Î±=0, Î³=0, Î´=0, Î±_t=0.14, Î»=10000, n=2, p=0, ðœ‰=8)

formula <- function(t,y,parms){
  with(as.list(c(y,parms)),{
    
          Hi <- Hi0 + Hi1
          Fi <- Fi0 + Fi1
          Zi <- Hi + Fi
    
          dHi0 = b*( ( (Zi)**n ) / (Îº**n+(Zi)**n) ) -Ïƒ1 * Hi0+Ïƒ2 * (Fi/Zi) * Fi0 - Î·0 * Hi0 - Î±* Hi0* ( Ei / Î»+Ei)

          dHi1 = -Ïƒ1 * Hi1 + Ïƒ2 * (Fi/Zi) * Fi1 -Î·1 * Hi1+ Î± * Hi0 * (Ei / (Î»+Ei))

          dFi0 = Ïƒ1 * Hi0 - (Ïƒ2 * (Fi/Zi) +Ï•0) *Fi0

          dFi1 = Ïƒ1 * Hi1 - (Ïƒ2 * (Fi / Zi) + Ï•1) *Fi1
            
          dEi <- Î³ * Hi1 - Î´ * Ei - Î±_t * Hi * (Ei / Î» + Ei)
          
          grid <- c(2, 4, 5, 23, 5, 10, 7)
          dEk <- lim((1 - ðœ‰* p) * Ek + p * grid * Ei)[2]
          print(lim((1 - ðœ‰* p) * Ek + p * grid * Ei))
          
          return(list(c(dHi0, dHi1, dFi0, dFi1, dEi, dEk)))
       }
       )
}
state = c(Hi0=10**4, Hi1=0, Fi0=10**4, Fi1=0, Ei=0, Ek=0)
times <- seq(0, 364 / 4,  by = 1)

gen_formula <- function(state) {
  out.spring <- as.data.frame(ode(times = times, y = state, parms = parameters.spring, func = formula, method = "euler"))

  state <- c(Hi0=out.spring[nrow(out.spring), 2], Hi1=out.spring[nrow(out.spring), 3], Fi0=out.spring[nrow(out.spring), 4], Fi1=out.spring[nrow(out.spring), 5], Ei=out.spring[nrow(out.spring), 6], Ek=out.spring[nrow(out.spring), 7])
  out.summer <- as.data.frame(ode(times = times, y = state, parms = parameters.summer, func = formula, method = "euler"))

  state <- c(Hi0=out.summer[nrow(out.summer), 2], Hi1=out.summer[nrow(out.summer), 3], Fi0=out.summer[nrow(out.summer), 4], Fi1=out.summer[nrow(out.summer), 5], Ei=out.summer[nrow(out.summer), 6], Ek=out.summer[nrow(out.summer), 7])
  out.fall <- as.data.frame(ode(times = times, y = state, parms = parameters.fall, func = formula, method = "euler"))

  state <- c(Hi0=out.fall[nrow(out.fall), 2], Hi1=out.fall[nrow(out.fall), 3], Fi0=out.fall[nrow(out.fall), 4], Fi1=out.fall[nrow(out.fall), 5], Ei=out.fall[nrow(out.fall), 6], Ek=out.fall[nrow(out.fall), 7])
  out.winter <- as.data.frame(ode(times = times, y = state, parms = parameters.winter, func = formula, method = "euler"))  
  
  out.summer$time <- out.summer$time+ (364/4)
  out.fall$time <- out.fall$time + 2*(364/4)
  out.winter$time <- out.winter$time + 3*(364/4)
  
  out.year <- rbind(out.spring, out.summer, out.fall, out.winter)
  return(list(out.year, out.winter))
}

out.1 <- gen_formula(state)

out.winter <- as.data.frame(out.1[2])
state <- c(Hi0=out.winter[nrow(out.winter), 2], Hi1=out.winter[nrow(out.winter), 3], Fi0=out.winter[nrow(out.winter), 4], Fi1=out.winter[nrow(out.winter), 5], Ei=out.winter[nrow(out.winter), 6], Ek=out.winter[nrow(out.winter), 7])
out.2 <- gen_formula(state)

out.winter <- as.data.frame(out.2[1])
state <- c(Hi0=out.winter[nrow(out.winter), 2], Hi1=out.winter[nrow(out.winter), 3], Fi0=out.winter[nrow(out.winter), 4], Fi1=out.winter[nrow(out.winter), 5], Ei=out.winter[nrow(out.winter), 6], Ek=out.winter[nrow(out.winter), 7])
out.3 <- gen_formula(state)

out.1.frame <- as.data.frame(out.1[1])
out.2.frame <- as.data.frame(out.2[1])
out.3.frame <- as.data.frame(out.3[1])


out.2.frame$time <- out.2.frame$time + 365
out.3.frame$time <- out.3.frame$time + 2*365
out.year <- as.data.frame(rbind(out.1.frame, out.2.frame, out.3.frame))
#out.year$time <- c(1:nrow(out.year))

plot(out.year$time, out.year$Hi0, type="l", ylim=c(0, 35000), xaxt="n")
lines(out.year$time, out.year$Fi0, lty=2, col=rainbow(1))
lines(out.year$time, out.year$Hi1, lty=3, col=rainbow(2)[2])
lines(out.year$time, out.year$Fi1, lty=4, col=rainbow(3)[3])
axis(1, at=seq(from=1, to=364*3, by = 364 / 4), labels=c("Sp", "S", "F", "W", "Sp", "S", "F", "W", "Sp", "S", "F", "W"))
legend(965, 36400, legend = c("H0", "H1", "F0", "F1"), lty = c(1, 2, 3, 4), title = "Subgroup", xpd="NA", col=rainbow(3))
plot(out.year$Ei, xaxt="n", type="l")
axis(1, at=seq(from=1, to=364*3, by = 364 / 4), labels=c("Sp", "S", "F", "W", "Sp", "S", "F", "W", "Sp", "S", "F", "W"))
```
```{r}
out.years <- data.frame()

index <- 0
winter.state <- c(Hi0=10**4, Hi1=0, Fi0=10**4, Fi1=0, Ei=0, Ek=0.1)
while (index < 51) {
  index <- index + 1
  
  out.year <- as.data.frame(gen_formula(winter.state))
  out.year$time <- out.year$time + 364 * index - 1
  out.years <- rbind(out.years, out.year)
  winter.state <- c(Hi0=out.year[nrow(out.year), 2], Hi1=out.year[nrow(out.year), 3], Fi0=out.year[nrow(out.year), 4], Fi1=out.year[nrow(out.year), 5], Ei=out.year[nrow(out.year), 6], Ek=out.year[nrow(out.year), 7])
  
}

plot(out.years$Hi0 ~ out.years$time, type="l")
```

```{r}
state = c(Hi0=10**4, Hi1=0, Fi0=10**4, Fi1=0, Ei=0, Ek=0.1)

out.spring <- as.data.frame(ode(times = times, y = state, parms = parameters.spring, func = formula, method = "euler"))
plot(out.spring$Ek)
```